# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

language: python
python:
    - 3.6

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install flake8

# command to run tests, e.g. python setup.py test
script:
    - make lint
    # This won't work because all the dependancies, need the docker image
    # - make coverage

