#!/usr/bin/env python

import argparse
import os

from weather_forecast_retrieval import hrrr


def run():

    parser = argparse.ArgumentParser(description='Run the data retrieval for HRRR model')
    parser.add_argument('config_file', metavar='F', type=str,
                        help='Path to config file')

    args = parser.parse_args()

    if os.path.isfile(args.config_file):
        #hrrr.HRRR(args.config_file).retrieve_grib_filter()
        # hrrr.HRRR(args.config_file).retrieve_ftp()
        hrrr.HRRR(args.config_file).retrieve_http_by_date()

    else:
        raise IOError('File does not exist.')


if __name__ == '__main__':
    run()
