#!/usr/bin/env python

import argparse
import os

from weather_forecast_retrieval.data.hrrr import HttpRetrieval


def run():

    parser = argparse.ArgumentParser(description='Run the data retrieval for HRRR model')
    parser.add_argument('config_file', metavar='F', type=str,
                        help='Path to config file')

    args = parser.parse_args()

    if os.path.isfile(args.config_file):
        HttpRetrieval(args.config_file).fetch_by_date()

    else:
        raise IOError('File does not exist.')


if __name__ == '__main__':
    run()
